"""Pure song and steel-event timeline primitives shared by both products."""

from packages.song_model.core import (
    SCHEMA_VERSION,
    Articulation,
    ChordBody,
    ClockDomain,
    ClockParentMapping,
    FretboardPosition,
    MechanicalValidity,
    NoteState,
    SelectionState,
    SongStructure,
    SongTimeline,
    SteelBody,
    SteelNote,
    TimedEvent,
    TimelineValidationError,
    Transition,
    ValidationIssue,
    canonical_timeline_json,
    map_clock_range_to_root,
    select_event,
    timeline_digest,
    timeline_from_dict,
    timeline_to_dict,
    validate_timeline,
)

__all__ = (
    "SCHEMA_VERSION",
    "Articulation",
    "ChordBody",
    "ClockDomain",
    "ClockParentMapping",
    "FretboardPosition",
    "MechanicalValidity",
    "NoteState",
    "SelectionState",
    "SongStructure",
    "SongTimeline",
    "SteelBody",
    "SteelNote",
    "TimedEvent",
    "TimelineValidationError",
    "Transition",
    "ValidationIssue",
    "canonical_timeline_json",
    "map_clock_range_to_root",
    "select_event",
    "timeline_digest",
    "timeline_from_dict",
    "timeline_to_dict",
    "validate_timeline",
)
