// The two client functions are serialized into nonce-bearing inline scripts.
// @ts-nocheck
function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

const sharedStyles = `
:root{color-scheme:dark;--bg:#111313;--panel:#1b1e1d;--line:#3b403e;--text:#f6f2e8;--muted:#b8b2a8;--red:#ff3f20;--gold:#e3bd78}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}button,input,select{font:inherit}button{cursor:pointer}.shell{width:min(1240px,calc(100% - 32px));margin:auto;padding:28px 0 64px}.eyebrow{color:var(--red);font-weight:850;letter-spacing:.12em;text-transform:uppercase;font-size:11px}h1,h2,h3,p{margin-top:0}.panel{border:1px solid var(--line);border-radius:8px;background:var(--panel);padding:18px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.field{display:grid;gap:6px;color:var(--muted);font-size:12px}.field input,.field select{width:100%;min-height:42px;border:1px solid var(--line);border-radius:6px;background:#0d0f0f;color:var(--text);padding:8px 10px}.actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.primary,.secondary{min-height:42px;border:1px solid var(--red);border-radius:6px;padding:0 14px;background:var(--red);color:white;font-weight:800}.secondary{background:transparent;border-color:var(--line);color:var(--text)}.status{color:var(--muted);font-size:13px;min-height:20px}.danger{color:#ff9a87}.uncertain{color:var(--gold)}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;border-bottom:1px solid var(--line);padding:8px;vertical-align:top}tr.active{outline:1px solid var(--red);background:#2a1915}td input{max-width:140px;background:#0d0f0f;color:var(--text);border:1px solid var(--line);border-radius:4px;padding:6px}audio,video{width:100%;margin:8px 0}.hidden{display:none!important}.pill{display:inline-flex;border:1px solid var(--line);border-radius:999px;padding:4px 8px;color:var(--muted);font-size:11px}.project{display:grid;gap:8px;text-align:left;width:100%;border:1px solid var(--line);border-radius:8px;background:#151817;color:var(--text);padding:14px}.wave{height:76px;width:100%;background:#0c0e0e;border:1px solid var(--line);border-radius:6px}@media(max-width:720px){.shell{width:min(100% - 20px,1240px)}table{display:block;overflow:auto}.panel{padding:13px}}
`;

export function authorHtml(nonce: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Travis Companion Studio</title><style nonce="${nonce}">${sharedStyles}</style></head><body>
  <main class="shell"><p class="eyebrow">Travis Toy Tutorials</p><h1>Companion Studio</h1><p class="status">Upload the lesson, mark the passages, review the generated music, then publish an immutable student revision.</p>
  <section id="chooser"><form id="create" class="panel"><h2>New lesson</h2><div class="grid">
    <label class="field">Title<input name="title" required></label><label class="field">Lesson slug<input name="slug" pattern="[a-z0-9-]+" required></label>
    <label class="field">Teachable course ID<input name="courseId" required></label><label class="field">Teachable lesson ID<input name="lessonId" required></label>
    <label class="field">Key<input name="key" value="D" required></label><label class="field">Meter<input name="meter" value="4/4" required></label>
  </div><p><button class="primary">Create lesson</button></p><p id="create-status" class="status"></p></form><section class="panel"><h2>Lessons</h2><div id="projects" class="grid"></div></section></section>
  <section id="workspace" class="hidden"><div class="actions"><button id="back" class="secondary">← Lessons</button><span id="project-state" class="pill"></span><span id="save-state" class="status"></span></div><h2 id="project-title"></h2>
    <section class="panel"><h3>1 · Media</h3><div class="grid"><label class="field">Lesson video (MP4/MOV)<input id="video-file" type="file" accept="video/mp4,video/quicktime"></label><label class="field">Backing MP3<input id="track-file" type="file" accept="audio/mpeg"></label></div><div id="assets"></div></section>
    <section class="panel"><h3>2 · Select performance passages</h3><video id="lesson-video" controls></video><div class="actions"><button id="passage-start" class="secondary">Use video time as start</button><button id="passage-end" class="secondary">Use video time as end</button><button id="track-start" class="secondary">Use track time as sync start</button><button id="track-end" class="secondary">Use track time as sync end</button></div><audio id="primary-audio" controls></audio><div class="actions"><label class="field">Speed<select id="speed"><option value="0.5">50%</option><option value="0.75">75%</option><option value="1" selected>100%</option><option value="1.25">125%</option></select></label><button id="loop-range" class="secondary">Loop marked track range</button><button id="clear-loop" class="secondary">Clear loop</button></div><canvas id="wave" class="wave"></canvas><div class="grid"><label class="field">Passage label<input id="passage-label" value="Taught passage"></label><label class="field">Video start ms<input id="video-start" type="number" min="0"></label><label class="field">Video end ms<input id="video-end" type="number" min="1"></label><label class="field">Track start ms<input id="track-range-start" type="number" min="0"></label><label class="field">Track end ms<input id="track-range-end" type="number" min="1"></label></div><p><button id="add-passage" class="primary">Add passage</button></p><div id="passages"></div></section>
    <section class="panel"><h3>3 · Analyze</h3><p class="status">The private runner generates a full chord chart and tab candidates for the selected passages.</p><div class="actions"><button id="analyze" class="primary">Analyze lesson</button><button id="refresh" class="secondary">Refresh status</button></div><p id="analysis-status" class="status"></p></section>
    <section class="panel"><h3>4 · Review full-song chords</h3><table><thead><tr><th>Start</th><th>End</th><th>Chord</th><th>NNS</th><th>Section</th><th>Status</th><th>Actions</th></tr></thead><tbody id="chords"></tbody></table></section>
    <section class="panel"><h3>5 · Review tablature</h3><div id="tab-editor"></div></section>
    <section class="panel"><h3>6 · Publish</h3><p class="status">Uncertain music may publish with a visible marker. Invalid timing or mechanics cannot.</p><div class="actions"><button id="validate" class="secondary">Validate</button><button id="publish" class="primary">Publish revision</button><select id="revisions"></select><button id="rollback" class="secondary">Roll back</button></div><p id="publish-status" class="status"></p></section>
  </section></main><script nonce="${nonce}">const __name=(target)=>target;${authorClient.toString()};authorClient();</script></body></html>`;
}

function authorClient() {
const $=(s)=>document.querySelector(s);let active=null;let saveTimer=null;const headers={"Content-Type":"application/json","X-Travis-Local-Author":"1"};
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});if(!response.ok){let message=response.statusText;try{message=(await response.json()).error||message}catch{}throw new Error(message)}return response.status===204?null:response.json()}
function message(node,text,error=false){node.textContent=text;node.classList.toggle("danger",error)}
async function list(){const data=await api("/api/author/projects");const mount=$("#projects");mount.innerHTML="";(data.projects||[]).forEach(project=>{const button=document.createElement("button");button.className="project";button.innerHTML=`<strong>${escapeText(project.title)}</strong><span>${escapeText(project.slug)}</span><span class="pill">${escapeText(project.state)}</span>`;button.onclick=()=>openProject(project.id);mount.append(button)})}
function escapeText(value){return String(value??"").replace(/[&<>\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]))}
$("#create").onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));try{const data=await api("/api/author/projects",{method:"POST",body:JSON.stringify(values)});event.target.reset();await list();await openProject(data.project.id)}catch(error){message($("#create-status"),error.message,true)}};
async function openProject(id){const data=await api(`/api/author/projects/${id}`);active=data;$("#chooser").classList.add("hidden");$("#workspace").classList.remove("hidden");render()}
$("#back").onclick=()=>{$("#workspace").classList.add("hidden");$("#chooser").classList.remove("hidden");active=null;list()};
function render(){
  if(!active)return;const {project,assets,revisions,jobs=[]}=active;$("#project-title").textContent=project.title;$("#project-state").textContent=project.state;const latestJob=jobs[0];$("#analysis-status").textContent=project.state==="processing"?`${latestJob?.progressMessage||"Waiting for the private analysis runner…"}${latestJob?.progress?` · ${Math.round(latestJob.progress*100)}%`:""}`:latestJob?.error||project.state;
  const assetMount=$("#assets");assetMount.innerHTML="";assets.forEach(asset=>{const row=document.createElement("div");row.className="panel";row.innerHTML=`<div class="actions"><strong>${escapeText(asset.label||asset.fileName)}</strong><span class="pill">${escapeText(asset.kind)}</span><span class="status">${escapeText(asset.status)}</span>${asset.kind==="backing_track"?`<label>Label <input data-label="${asset.id}" value="${escapeText(asset.label||asset.fileName)}"></label><label><input data-primary="${asset.id}" type="radio" name="primary" ${asset.isPrimary?"checked":""}> Primary</label><label><input data-visible="${asset.id}" type="checkbox" ${asset.visibleToLearners?"checked":""}> Student player</label><label><input data-download="${asset.id}" type="checkbox" ${asset.downloadable?"checked":""}> Download</label>`:""}</div>`;assetMount.append(row)});assetMount.querySelectorAll("[data-primary],[data-visible],[data-download],[data-label]").forEach(input=>input.onchange=()=>configureAsset(input));
  const video=assets.find(item=>item.kind==="lesson_video"&&item.status==="uploaded");const primary=assets.find(item=>item.isPrimary);if(video)$("#lesson-video").src=`/api/author/assets/${video.id}?local=1`;if(primary){$("#primary-audio").src=`/api/author/assets/${primary.id}?local=1`;drawWaveform(primary.id)}
  renderPassages();renderDraft();const select=$("#revisions");select.innerHTML="";revisions.forEach(revision=>{const option=document.createElement("option");option.value=revision.revision;option.textContent=`${revision.revision} · ${revision.publishedAt}`;select.append(option)})
}
async function drawWaveform(assetId){try{const response=await fetch(`/api/author/assets/${assetId}?local=1`,{headers:{"X-Travis-Local-Author":"1"}});if(!response.ok)return;const audioContext=new AudioContext();const decoded=await audioContext.decodeAudioData(await response.arrayBuffer());const samples=decoded.getChannelData(0);const canvas=$("#wave");const ratio=devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(canvas.clientWidth*ratio));canvas.height=Math.max(1,Math.floor(canvas.clientHeight*ratio));const context=canvas.getContext("2d");context.clearRect(0,0,canvas.width,canvas.height);context.strokeStyle="#ff3f20";context.beginPath();const middle=canvas.height/2;for(let x=0;x<canvas.width;x++){const start=Math.floor(x*samples.length/canvas.width);const end=Math.max(start+1,Math.floor((x+1)*samples.length/canvas.width));let peak=0;for(let index=start;index<end;index++)peak=Math.max(peak,Math.abs(samples[index]||0));context.moveTo(x,middle-peak*middle);context.lineTo(x,middle+peak*middle)}context.stroke();await audioContext.close()}catch{}}
async function configureAsset(input){try{await api(`/api/author/assets/${input.dataset.primary||input.dataset.visible||input.dataset.download||input.dataset.label}`,{method:"PATCH",body:JSON.stringify({primary:input.dataset.primary?input.checked:undefined,visibleToLearners:input.dataset.visible?input.checked:undefined,downloadable:input.dataset.download?input.checked:undefined,label:input.dataset.label?input.value:undefined})});await openProject(active.project.id)}catch(error){alert(error.message)}}
async function upload(file,kind){const created=await api(`/api/author/projects/${active.project.id}/uploads`,{method:"POST",body:JSON.stringify({kind,fileName:file.name,contentType:file.type,size:file.size,label:file.name})});const partSize=8*1024*1024;const parts=[];for(let offset=0,number=1;offset<file.size;offset+=partSize,number++){message($("#save-state"),`Uploading ${file.name}: ${Math.round(offset/file.size*100)}%`);const response=await fetch(`/api/author/uploads/${created.asset.id}/parts/${number}?uploadId=${encodeURIComponent(created.uploadId)}`,{method:"PUT",body:file.slice(offset,Math.min(file.size,offset+partSize)),headers:{"X-Travis-Local-Author":"1"}});if(!response.ok)throw new Error("Upload part failed.");parts.push(await response.json())}await api(`/api/author/uploads/${created.asset.id}/complete`,{method:"POST",body:JSON.stringify({uploadId:created.uploadId,parts})});message($("#save-state"),"Upload complete");await openProject(active.project.id)}
$("#video-file").onchange=event=>event.target.files[0]&&upload(event.target.files[0],"lesson_video").catch(error=>message($("#save-state"),error.message,true));$("#track-file").onchange=event=>event.target.files[0]&&upload(event.target.files[0],"backing_track").catch(error=>message($("#save-state"),error.message,true));
$("#passage-start").onclick=()=>$("#video-start").value=Math.round($("#lesson-video").currentTime*1000);$("#passage-end").onclick=()=>$("#video-end").value=Math.round($("#lesson-video").currentTime*1000);$("#track-start").onclick=()=>$("#track-range-start").value=Math.round($("#primary-audio").currentTime*1000);$("#track-end").onclick=()=>$("#track-range-end").value=Math.round($("#primary-audio").currentTime*1000);
let loopRange=null;$("#speed").onchange=()=>{$("#primary-audio").playbackRate=Number($("#speed").value);$("#lesson-video").playbackRate=Number($("#speed").value)};$("#loop-range").onclick=()=>{const start=Number($("#track-range-start").value);const end=Number($("#track-range-end").value);if(end>start){loopRange={start:start/1000,end:end/1000};$("#primary-audio").currentTime=loopRange.start;$("#primary-audio").play()}};$("#clear-loop").onclick=()=>loopRange=null;$("#primary-audio").ontimeupdate=()=>{const audio=$("#primary-audio");if(loopRange&&audio.currentTime>=loopRange.end)audio.currentTime=loopRange.start;const now=audio.currentTime*1000;$("#chords").querySelectorAll("tr").forEach((row,index)=>{const chord=active?.project?.draft?.songChordTimeline?.[index];row.classList.toggle("active",Boolean(chord&&now>=chord.startMs&&now<chord.endMs))})};$("#wave").onclick=event=>{const bounds=event.currentTarget.getBoundingClientRect();const audio=$("#primary-audio");if(Number.isFinite(audio.duration))audio.currentTime=Math.max(0,Math.min(1,(event.clientX-bounds.left)/bounds.width))*audio.duration};
$("#add-passage").onclick=()=>{const draft=active.project.draft;draft.passages.push({id:`passage-${crypto.randomUUID()}`,label:$("#passage-label").value,videoRange:{startMs:Number($("#video-start").value),endMs:Number($("#video-end").value)},trackRange:{startMs:Number($("#track-range-start").value),endMs:Number($("#track-range-end").value)},alignment:{status:"manual",confidence:1},tabEvents:[]});queueSave("Added passage");renderPassages()};
function renderPassages(){const mount=$("#passages");mount.innerHTML="";(active.project.draft.passages||[]).forEach((passage,index)=>{const row=document.createElement("div");row.className="panel";row.innerHTML=`<div class="grid"><label class="field">Label<input data-passage="${index}:label" value="${escapeText(passage.label)}"></label><label class="field">Video start<input type="number" data-passage="${index}:videoStart" value="${passage.videoRange.startMs}"></label><label class="field">Video end<input type="number" data-passage="${index}:videoEnd" value="${passage.videoRange.endMs}"></label><label class="field">Track start<input type="number" data-passage="${index}:trackStart" value="${passage.trackRange.startMs}"></label><label class="field">Track end<input type="number" data-passage="${index}:trackEnd" value="${passage.trackRange.endMs}"></label></div><button class="secondary" data-remove-passage="${index}">Remove</button>`;mount.append(row)});mount.querySelectorAll("[data-passage]").forEach(input=>input.oninput=()=>{const [index,key]=input.dataset.passage.split(":");const passage=active.project.draft.passages[Number(index)];if(key==="label")passage.label=input.value;else if(key==="videoStart")passage.videoRange.startMs=Number(input.value);else if(key==="videoEnd")passage.videoRange.endMs=Number(input.value);else if(key==="trackStart")passage.trackRange.startMs=Number(input.value);else if(key==="trackEnd")passage.trackRange.endMs=Number(input.value);passage.alignment={status:"manual",confidence:1,method:"travis_manual"};queueSave("Edited passage timing")});mount.querySelectorAll("[data-remove-passage]").forEach(button=>button.onclick=()=>{active.project.draft.passages.splice(Number(button.dataset.removePassage),1);queueSave("Removed passage");renderPassages();renderDraft()})}
function renderDraft(){
  const draft=active.project.draft;const chordMount=$("#chords");chordMount.innerHTML="";(draft.songChordTimeline||[]).forEach((chord,index)=>{const row=document.createElement("tr");row.innerHTML=`<td><input data-chord="${index}" data-key="startMs" type="number" value="${chord.startMs}"></td><td><input data-chord="${index}" data-key="endMs" type="number" value="${chord.endMs}"></td><td><input data-chord="${index}" data-key="symbol" value="${escapeText(chord.symbol||"")}" placeholder="?"></td><td><input data-chord="${index}" data-key="nns" value="${escapeText(chord.nns||"")}"></td><td><input data-chord="${index}" data-key="sectionLabel" value="${escapeText(chord.sectionLabel||"")}"></td><td class="${chord.reviewStatus==="uncertain"?"uncertain":""}">${escapeText(chord.reviewStatus)}</td><td><button class="secondary" data-split-chord="${index}">Split</button>${index<draft.songChordTimeline.length-1?`<button class="secondary" data-merge-chord="${index}">Merge next</button>`:""}</td>`;chordMount.append(row)});
  chordMount.querySelectorAll("input").forEach(input=>input.oninput=()=>{const chord=draft.songChordTimeline[Number(input.dataset.chord)];chord[input.dataset.key]=input.type==="number"?Number(input.value):input.value||null;if(input.dataset.key==="symbol")chord.reviewStatus=input.value?"approved":"uncertain";queueSave("Edited chord chart")});
  chordMount.querySelectorAll("[data-split-chord]").forEach(button=>button.onclick=()=>{const index=Number(button.dataset.splitChord);const chord=draft.songChordTimeline[index];const midpoint=Math.round((chord.startMs+chord.endMs)/2);if(midpoint<=chord.startMs||midpoint>=chord.endMs)return;const next={...structuredClone(chord),id:`chord-${crypto.randomUUID()}`,startMs:midpoint};chord.endMs=midpoint;draft.songChordTimeline.splice(index+1,0,next);queueSave("Split chord span");renderDraft()});
  chordMount.querySelectorAll("[data-merge-chord]").forEach(button=>button.onclick=()=>{const index=Number(button.dataset.mergeChord);const chord=draft.songChordTimeline[index];const next=draft.songChordTimeline[index+1];if(!next)return;chord.endMs=next.endMs;draft.songChordTimeline.splice(index+1,1);queueSave("Merged chord spans");renderDraft()});
  const tab=$("#tab-editor");tab.innerHTML="";(draft.passages||[]).forEach((passage,pIndex)=>{const section=document.createElement("section");section.innerHTML=`<h4>${escapeText(passage.label)}</h4><table><thead><tr><th>Start</th><th>End</th><th>String</th><th>Fret</th><th>Pitch</th><th>Controls</th><th>Technique</th><th>Alternatives</th><th>Status</th><th></th></tr></thead><tbody></tbody></table><button class="secondary" data-add-event="${pIndex}">Add event</button>`;const body=section.querySelector("tbody");(passage.tabEvents||[]).forEach((event,eIndex)=>{const alternatives=(event.routeAlternatives||[]).map(item=>typeof item==="string"?item:item.label||item.id||JSON.stringify(item)).join(", ");(event.notes||[]).forEach((note,nIndex)=>{const row=document.createElement("tr");row.innerHTML=`<td>${nIndex===0?`<input type="number" data-tab="${pIndex}:${eIndex}:startMs" value="${event.startMs}">`:""}</td><td>${nIndex===0?`<input type="number" data-tab="${pIndex}:${eIndex}:endMs" value="${event.endMs}">`:""}</td><td><input type="number" data-note="${pIndex}:${eIndex}:${nIndex}:string" value="${note.string}"></td><td><input type="number" data-note="${pIndex}:${eIndex}:${nIndex}:fret" value="${note.fret}"></td><td><input type="number" data-note="${pIndex}:${eIndex}:${nIndex}:pitchValue" value="${note.pitchValue??""}"></td><td><input data-note="${pIndex}:${eIndex}:${nIndex}:controls" value="${escapeText((note.controls||[]).join("+"))}"></td><td><input data-note="${pIndex}:${eIndex}:${nIndex}:technique" value="${escapeText(note.technique||"pick")}"></td><td>${nIndex===0?`<input data-tab="${pIndex}:${eIndex}:routeAlternatives" value="${escapeText(alternatives)}">`:""}</td><td class="${event.reviewStatus==="generated_unconfirmed"?"uncertain":""}">${nIndex===0?escapeText(event.reviewStatus):""}</td><td><button class="secondary" data-delete-note="${pIndex}:${eIndex}:${nIndex}">Delete note</button>${nIndex===0?`<button class="secondary" data-add-note="${pIndex}:${eIndex}">Add note</button><button class="secondary" data-delete-event="${pIndex}:${eIndex}">Delete event</button>`:""}</td>`;body.append(row)})});tab.append(section)});
  tab.querySelectorAll("input").forEach(input=>input.oninput=()=>{if(input.dataset.tab){const [p,e,key]=input.dataset.tab.split(":");const event=draft.passages[Number(p)].tabEvents[Number(e)];event[key]=key==="routeAlternatives"?input.value.split(",").map(v=>v.trim()).filter(Boolean):Number(input.value);event.reviewStatus="approved"}else{const [p,e,n,key]=input.dataset.note.split(":");const event=draft.passages[Number(p)].tabEvents[Number(e)];const note=event.notes[Number(n)];if(key==="controls")note[key]=input.value.split("+").map(v=>v.trim()).filter(Boolean);else if(key==="technique")note[key]=input.value;else if(key==="pitchValue"){if(input.value)note[key]=Number(input.value);else delete note[key]}else{note[key]=Number(input.value);delete note.pitchValue}event.reviewStatus="approved"}queueSave("Edited tablature")});
  tab.querySelectorAll("[data-add-event]").forEach(button=>button.onclick=()=>{const passage=draft.passages[Number(button.dataset.addEvent)];const last=passage.tabEvents.at(-1);const start=Math.max(passage.trackRange.startMs,last?.endMs||passage.trackRange.startMs);const end=Math.min(passage.trackRange.endMs,start+250);if(end<=start)return;passage.tabEvents.push({id:`event-${crypto.randomUUID()}`,startMs:start,endMs:end,notes:[{string:3,fret:0,controls:[],technique:"pick"}],reviewStatus:"approved",confidence:null,provenance:"travis_manual"});queueSave("Added tab event");renderDraft()});
  tab.querySelectorAll("[data-add-note]").forEach(button=>button.onclick=()=>{const [p,e]=button.dataset.addNote.split(":");draft.passages[Number(p)].tabEvents[Number(e)].notes.push({string:3,fret:0,controls:[],technique:"pick"});queueSave("Added tab note");renderDraft()});tab.querySelectorAll("[data-delete-note]").forEach(button=>button.onclick=()=>{const [p,e,n]=button.dataset.deleteNote.split(":");const event=draft.passages[Number(p)].tabEvents[Number(e)];if(event.notes.length<=1)return;event.notes.splice(Number(n),1);queueSave("Deleted tab note");renderDraft()});tab.querySelectorAll("[data-delete-event]").forEach(button=>button.onclick=()=>{const [p,e]=button.dataset.deleteEvent.split(":");draft.passages[Number(p)].tabEvents.splice(Number(e),1);queueSave("Deleted tab event");renderDraft()})
}
function queueSave(summary){clearTimeout(saveTimer);message($("#save-state"),"Unsaved changes");saveTimer=setTimeout(()=>save(summary),500)}
async function save(summary){try{const result=await api(`/api/author/projects/${active.project.id}/draft`,{method:"PATCH",body:JSON.stringify({expectedVersion:active.project.draftVersion,draft:active.project.draft,summary})});active.project.draftVersion=result.draftVersion;message($("#save-state"),"Saved");if(["review_ready","published"].includes(active.project.state)){try{await api(`/api/author/projects/${active.project.id}/validate`,{method:"POST",body:"{}"});message($("#publish-status"),"Technical validation passes.")}catch(validationError){message($("#publish-status"),validationError.message,true)}}}catch(error){message($("#save-state"),`${error.message} Refresh before editing further.`,true)}}
$("#analyze").onclick=async()=>{try{await save("Saved passages for analysis");await api(`/api/author/projects/${active.project.id}/analyze`,{method:"POST",body:"{}"});await openProject(active.project.id)}catch(error){message($("#analysis-status"),error.message,true)}};$("#refresh").onclick=()=>openProject(active.project.id);
$("#validate").onclick=async()=>{try{await api(`/api/author/projects/${active.project.id}/validate`,{method:"POST",body:"{}"});message($("#publish-status"),"Draft passes technical validation.")}catch(error){message($("#publish-status"),error.message,true)}};
$("#publish").onclick=async()=>{try{await save("Pre-publish save");const result=await api(`/api/author/projects/${active.project.id}/publish`,{method:"POST",body:"{}"});message($("#publish-status"),`Published ${result.revision}`);await openProject(active.project.id)}catch(error){message($("#publish-status"),error.message,true)}};$("#rollback").onclick=async()=>{try{const revision=$("#revisions").value;if(!revision)throw new Error("Choose a revision.");await api(`/api/author/projects/${active.project.id}/rollback`,{method:"POST",body:JSON.stringify({revision})});message($("#publish-status"),`Rolled back to ${revision}`);await openProject(active.project.id)}catch(error){message($("#publish-status"),error.message,true)}};
list().catch(error=>message($("#create-status"),error.message,true));
}

export function embedHtml(nonce: string, slug: string): string {
  const safeSlug = escapeHtml(slug);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lesson companion</title><style nonce="${nonce}">${sharedStyles}.shell{padding-top:18px}.chart{display:flex;gap:8px;overflow:auto;padding:6px 0}.chord{min-width:110px;border:1px solid var(--line);border-radius:6px;padding:9px}.chord.active{border-color:var(--red)}.tab-event{display:grid;grid-template-columns:90px 1fr auto;gap:10px;border-bottom:1px solid var(--line);padding:9px 0}.verify{text-align:center;padding:44px 20px}</style></head><body><main class="shell" data-slug="${safeSlug}"><section id="verify" class="panel verify"><p class="eyebrow">Travis Toy Tutorials</p><h1>Lesson companion</h1><p>Verify your Teachable enrollment to open the synchronized chart and tablature.</p><button id="verify-button" class="primary">Verify with Teachable</button><button id="dev-button" class="secondary hidden">Local preview</button><p id="status" class="status"></p></section><section id="companion" class="hidden"><p class="eyebrow">Lesson companion</p><h1 id="title"></h1><p id="meta" class="status"></p><audio id="audio" controls></audio><div id="chart" class="chart"></div><div id="tracks" class="panel"></div><div id="passage-list"></div><p><a id="pdf" class="secondary" target="_blank" rel="noopener">Printable PDF</a></p></section></main><script nonce="${nonce}">const __name=(target)=>target;${embedClient.toString()};embedClient();</script></body></html>`;
}

function embedClient() {
const root=document.querySelector("[data-slug]");const slug=root.dataset.slug;const verify=document.querySelector("#verify");const companion=document.querySelector("#companion");const status=document.querySelector("#status");let token=sessionStorage.getItem(`travis-companion:${slug}`)||"";
function fail(message){status.textContent=message;status.classList.add("danger")}
function textElement(tag,text,className=""){const node=document.createElement(tag);node.textContent=String(text??"");if(className)node.className=className;return node}
async function json(path,options={}){const response=await fetch(path,{...options,headers:{...(options.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})}});if(!response.ok){let message=response.statusText;try{message=(await response.json()).error||message}catch{}throw new Error(message)}return response.json()}
document.querySelector("#verify-button").onclick=()=>window.open(`/auth/teachable/start?lesson=${encodeURIComponent(slug)}`,"travis-companion-oauth","popup,width=520,height=700");
window.addEventListener("message",async event=>{if(event.origin!==location.origin||event.data?.type!=="travis-companion-code")return;try{const result=await json("/api/embed/exchange",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:event.data.code,slug})});token=result.token;sessionStorage.setItem(`travis-companion:${slug}`,token);await load()}catch(error){fail(error.message)}});
async function load(){try{
  const data=await json(`/api/embed/${encodeURIComponent(slug)}/artifact`);verify.classList.add("hidden");companion.classList.remove("hidden");document.querySelector("#title").textContent=data.lesson.title;document.querySelector("#meta").textContent=`${data.lesson.key} · ${data.lesson.meter} · ${data.revision}`;
  const primary=data.media.backingTracks.find(track=>track.primary);const audio=document.querySelector("#audio");audio.src=`/api/embed/${encodeURIComponent(slug)}/media/${encodeURIComponent(primary.assetId)}?token=${encodeURIComponent(token)}`;
  const chart=document.querySelector("#chart");chart.replaceChildren();data.songChordTimeline.forEach(chord=>{const node=document.createElement("button");node.className="chord";node.append(textElement("strong",chord.symbol||"?"),document.createElement("br"),textElement("span",chord.nns||""));if(chord.reviewStatus==="uncertain")node.append(document.createElement("br"),textElement("span","Unconfirmed","uncertain"));node.onclick=()=>audio.currentTime=chord.startMs/1000;chart.append(node)});
  const tracks=document.querySelector("#tracks");tracks.replaceChildren(textElement("h2","Backing tracks"));data.media.backingTracks.filter(track=>track.visibleToLearners).forEach(track=>{const row=document.createElement("div");row.className="panel";row.append(textElement("strong",track.label||track.fileName));if(!track.primary){const player=document.createElement("audio");player.controls=true;player.src=`/api/embed/${encodeURIComponent(slug)}/media/${encodeURIComponent(track.assetId)}?token=${encodeURIComponent(token)}`;row.append(player)}if(track.downloadable){const link=textElement("a","Download");link.href=`/api/embed/${encodeURIComponent(slug)}/media/${encodeURIComponent(track.assetId)}?download=1&token=${encodeURIComponent(token)}`;row.append(link)}tracks.append(row)});
  const list=document.querySelector("#passage-list");list.replaceChildren();data.passages.forEach(passage=>{const panel=document.createElement("section");panel.className="panel";panel.append(textElement("h2",passage.label));(passage.tabEvents||[]).forEach(event=>{const row=document.createElement("button");row.className="tab-event secondary";const notation=event.notes.map(note=>`S${note.string} · F${note.fret}${(note.controls||[]).length?` · ${(note.controls||[]).join("+")}`:""}`).join(" / ");row.append(textElement("span",`${(event.startMs/1000).toFixed(2)}s`),textElement("strong",notation),textElement("span",event.reviewStatus==="generated_unconfirmed"?"Unconfirmed":"Reviewed",event.reviewStatus==="generated_unconfirmed"?"uncertain":""));row.onclick=()=>audio.currentTime=event.startMs/1000;panel.append(row)});list.append(panel)});
  const pdf=document.querySelector("#pdf");pdf.href=`/api/embed/${encodeURIComponent(slug)}/pdf?token=${encodeURIComponent(token)}`;audio.ontimeupdate=()=>{const now=audio.currentTime*1000;chart.querySelectorAll(".chord").forEach((node,index)=>node.classList.toggle("active",now>=data.songChordTimeline[index].startMs&&now<data.songChordTimeline[index].endMs))}
}catch(error){token="";sessionStorage.removeItem(`travis-companion:${slug}`);fail(error.message)}}
fetch("/api/environment").then(response=>response.json()).then(env=>{if(env.development){const button=document.querySelector("#dev-button");button.classList.remove("hidden");button.onclick=async()=>{try{const result=await json(`/api/embed/${encodeURIComponent(slug)}/dev-token`,{method:"POST"});token=result.token;sessionStorage.setItem(`travis-companion:${slug}`,token);await load()}catch(error){fail(error.message)}}}});if(token)load();
}

export function oauthCallbackHtml(nonce: string, origin: string, code: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Access verified</title><style nonce="${nonce}">${sharedStyles}</style></head><body><main class="shell"><section class="panel verify"><h1>Access verified</h1><p>You can close this window.</p></section></main><script nonce="${nonce}">if(window.opener){window.opener.postMessage({type:"travis-companion-code",code:${JSON.stringify(code)}},${JSON.stringify(origin)});window.close()}</script></body></html>`;
}
